CREATE DATABASE data;
CREATE DATABASE auth;
CREATE DATABASE device;
GRANT ALL PRIVILEGES ON DATABASE data TO admin;
GRANT ALL PRIVILEGES ON DATABASE auth TO admin;
GRANT ALL PRIVILEGES ON DATABASE device TO admin;
