[package]
name = "web_api"
version = "0.0.1"
edition = "2024"
description = "web_api"
license = "GPL-3.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { workspace = true, features = ["tracing"] }
derive_more = { workspace = true }
greenhouse_core = { workspace = true, features = ["auth_service_dto"] }
greenhouse_macro = { workspace = true }
jsonwebtoken = { workspace = true }
reqwest = { workspace = true, features = ["json"] }
sentry = { workspace = true, features = ["debug-images", "tower"] }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
tokio = { workspace = true }
tower-cookies = { workspace = true }
tower-http = { workspace = true, features = ["trace", "cors"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tower-http = { workspace = true, features = ["trace", "cors"] }
sentry = { workspace = true, features = ["debug-images", "tower"] }
jsonwebtoken = { workspace = true }
urlencoding = { workspace = true }
uuid = { workspace = true, features = [
    "v4",
    "fast-rng",
    "macro-diagnostics",
    "serde",
] }
