version: '3'
services:
  smart-device-example:
    build:
      context: ./
      dockerfile: ./examples/hybrid_device/Dockerfile
    volumes:
      - ./docker/hybrid_device:/usr/local/bin/config
    ports:
      - "9099:9099"

  auth_service:
    build:
      context: ./
      dockerfile: ./services/auth_service/Dockerfile
    volumes:
      - ./docker/auth_service:/usr/local/bin/config
    ports:
      - "9091:5000"
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - backend

  data_storage_service:
    build:
      context: ./
      dockerfile: ./services/data_storage_service/Dockerfile
    volumes:
      - ./docker/data_storage_service:/usr/local/bin/config
    ports:
      - "9092:5000"
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - backend

  web_api:
    build:
      context: ./
      dockerfile: ./api/web/Dockerfile
    volumes:
      - ./docker/api_web:/usr/local/bin/config
    ports:
      - "9090:5100"
    depends_on:
      - auth_service
      - data_storage_service
    restart: unless-stopped
    networks:
      - backend
      - frontend

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend

volumes:
  db-data: {}

networks:
  frontend:
  backend: