-- Your SQL goes here
CREATE TABLE diary_entry (
    id UUID PRIMARY KEY,
    entry_date TIMESTAMP WITH TIME ZONE NOT NULL,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);